// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzyKtEKbUMt66t9Sfk_onbOcJNic_t5oc',
    appId: '1:619229942843:web:8eced8b46057a24b04f81e',
    messagingSenderId: '619229942843',
    projectId: 'unitrade-d74e9',
    authDomain: 'unitrade-d74e9.firebaseapp.com',
    storageBucket: 'unitrade-d74e9.firebasestorage.app',
    measurementId: 'G-6DPM2BCY97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGoUiJf1u9cLrkqU8qhLVCQUHDhCLdjk',
    appId: '1:619229942843:android:3b1fb17cd1d1740c04f81e',
    messagingSenderId: '619229942843',
    projectId: 'unitrade-d74e9',
    storageBucket: 'unitrade-d74e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGFJq_8UNND9exxcetJ9TVhgrcQys0KEE',
    appId: '1:619229942843:ios:247fb4f88ca5540004f81e',
    messagingSenderId: '619229942843',
    projectId: 'unitrade-d74e9',
    storageBucket: 'unitrade-d74e9.firebasestorage.app',
    iosClientId: '619229942843-50sl1gko7vefi8uun1bck1pvq698gnb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGFJq_8UNND9exxcetJ9TVhgrcQys0KEE',
    appId: '1:619229942843:ios:247fb4f88ca5540004f81e',
    messagingSenderId: '619229942843',
    projectId: 'unitrade-d74e9',
    storageBucket: 'unitrade-d74e9.firebasestorage.app',
    iosClientId: '619229942843-50sl1gko7vefi8uun1bck1pvq698gnb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzyKtEKbUMt66t9Sfk_onbOcJNic_t5oc',
    appId: '1:619229942843:web:f2bfb57302f49e7d04f81e',
    messagingSenderId: '619229942843',
    projectId: 'unitrade-d74e9',
    authDomain: 'unitrade-d74e9.firebaseapp.com',
    storageBucket: 'unitrade-d74e9.firebasestorage.app',
    measurementId: 'G-JR3HCW4472',
  );
}
